Fix/statistics values
kimberllyflorez/pancho-carbs pull request #18
Opened 2023-04-17 04:43 UTC by kimberllyflorez

2023-04-17 06:03 UTC, curregoz commented
@kimberllyflorez Please. Try to keep your commit messages more descriptive. `Advance` isn't a good message for a commit

2023-04-17 06:04 UTC, curregoz commented
Please add in the description on the PR what is the objective of this PR

2023-04-17 06:34 UTC, kimberllyflorez commented
The object in this PR is fix the value of calorie object in where we got 0.0 now is the correct value of the calculation calorie

2023-04-17 06:53 UTC, curregoz requested changes

2023-04-17 06:53 UTC, curregoz commented on lib/app/home/provider/home_provider.dart
> +        calorieObject: '0.0',
Its not necessary initialize values of the object HomeState here.

2023-04-17 06:53 UTC, curregoz commented on lib/app/home/provider/home_provider.dart
> +    getCalorieObjective();
You can join this two calls usin Rx.combine to emit only one time a state

2023-04-17 06:53 UTC, curregoz commented on lib/app/home/ui/pages/home_page.dart
> +    _homeProvider = locator<HomeProvider>();
This instace is not necessary.
Use provider object of PageState instead

2023-04-17 06:53 UTC, curregoz commented on lib/app/search_products/ui/pages/food_tracker_page.dart
> +    _foodItemsProvider = locator<FoodTrackerProvider>();
Same here.  Use provider object of PageState instead

2023-04-17 06:53 UTC, curregoz commented on lib/app/search_products/provider/food_traker_provider.dart
> +  List<FoodItemsModel> meals = [];
Create a state objetc for this provider

2023-04-17 06:53 UTC, curregoz commented on lib/domain/use_cases/user_data/level_activity/save_activity_lavel_use_case.dart
> +    PreferenceUtils.setInt(PreferenceConst.activity, level);
Avoid using the class PreferenceUtils. Use Storage and add this via DI

2023-04-18 03:23 UTC, kimberllyflorez commented on lib/domain/use_cases/user_data/level_activity/save_activity_lavel_use_case.dart
> +    PreferenceUtils.setInt(PreferenceConst.activity, level);
this is solved in another branch

2023-04-18 03:23 UTC, kimberllyflorez commented on lib/app/search_products/provider/food_traker_provider.dart
> +  List<FoodItemsModel> meals = [];
done

2023-04-18 03:23 UTC, kimberllyflorez commented on lib/app/search_products/ui/pages/food_tracker_page.dart
> +    _foodItemsProvider = locator<FoodTrackerProvider>();
sorry about that

2023-04-18 06:11 UTC, curregoz approved these changes

2023-04-18 11:01 UTC, merged